services:
  chat-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./websocket_system.db:/app/websocket_system.db
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - chat-network
 
  chat-dev:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./websocket_system.db:/app/websocket_system.db
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  chat-db: 